project:
  type: website
  output-dir: docs

website:
  title: "godfuf-blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



